basePath: /api
definitions:
  main.ErrorResponse:
    description: Error response
    properties:
      message:
        example: Invalid request body
        type: string
      status:
        example: 1
        type: integer
    type: object
  main.GetStudentsResponse:
    description: Get students response
    properties:
      data:
        items:
          $ref: '#/definitions/models.Student'
        type: array
      message:
        example: Get students successful!
        type: string
      status:
        example: 200
        type: integer
    type: object
  main.LoginData:
    description: Login response data
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1dGhmaSIsImV4cCI6MTc1NTMzMTU5NiwiaWF0IjoxNzU1MjQ1MTk2fQ.7WktpMm0AyyfXUR5x68Om7Pps9uR1resDlh2bz9C_J8
        type: string
    type: object
  main.LoginRequest:
    description: Login request payload
    properties:
      password:
        example: "123"
        type: string
      username:
        example: luthfi
        type: string
    type: object
  main.LoginResponse:
    description: Login response
    properties:
      data:
        $ref: '#/definitions/main.LoginData'
      message:
        example: Login successful!
        type: string
      status:
        example: 200
        type: integer
    type: object
  models.Student:
    properties:
      email:
        type: string
      id:
        type: integer
      major:
        type: string
      name:
        type: string
      nim:
        type: string
      semester:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: Error response
  title: Sistem Manajemen Mahasiswa
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/main.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/main.LoginResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: Failed to generate token
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: User login
      tags:
      - Authentication
  /students:
    get:
      consumes:
      - application/json
      description: Get all student data
      produces:
      - application/json
      responses:
        "200":
          description: Profile retrieved successfully
          schema:
            $ref: '#/definitions/main.GetStudentsResponse'
        "401":
          description: Authorization header required or Invalid token
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all student
      tags:
      - Students
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
